name: Test branch code

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build code test
      run: echo ${{ secrets.TEST }}
