# name: Pull Request Action
# on:
#   workflow_dispatch:

# jobs:
#   create-pull-request:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v2
#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v3.10.1
#         with:
#           token: ${{ secrets.PULL_REQUEST_TOKEN }}
#           commit-message: Auto Pull Request
#           title: Auto Pull Request
#           body: Auto-created Pull Request
#           branch: dev # The branch where you commit
#           base: main # Don't forget to specify the right base branch here    

name: Merge main to All Branches

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Merge main to All Branches
      run: |
        # Get the list of branches (excluding main)
        #branches=$(git branch -r | grep 'origin/main' | sed 's/origin\///')
        branches="dev"
        # Loop through each branch and merge main
        echo $pwd
        ls -lrt
        for branch in $branches; do
          # echo "$branch inside"
          # git checkout -b $branch
          # ls -lrt
          # echo "check out done"
          # git pull origin main
          # echo "pull done"
          # ls -lrt
          # git push origin $branch
          # echo "push done"


          # Create a branch for the pull request
          git checkout -b pr-branch-$branch

          # Merge changes from main
          git pull origin main
          
          # Push the changes and create a pull request
          git push origin pr-branch-$branch
          git fatch
          # Create pull request
          gh pr create --base pr-branch-$branch --head $branch --title "Merge from main" --body "Automated pull request to merge changes from main."


        done