name: Pull Request Action
on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.PULL_REQUEST_TOKEN }}
          commit-message: Auto Pull Request
          title: Auto Pull Request
          body: Auto-created Pull Request
          branch: dev # The branch where you commit
          base: main # Don't forget to specify the right base branch here    
